# only used for development
version: "3"
services:
  strapi:
    image: strapi/strapi:3.6.8-alpine
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_NAME: asktogether
      DATABASE_HOST: database
      DATABASE_USERNAME: asktogether_admin
      DATABASE_PASSWORD: youshallnotpass
      DATABASE_PORT: 5432
    volumes:
      - ./strapi:/srv/app
    depends_on:
      - database
    ports:
      - "1337:1337"

  database:
    image: postgres:9.6.24-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: asktogether_admin
      POSTGRES_PASSWORD: youshallnotpass
      POSTGRES_DB: asktogether
    volumes:
      - asktogether-db:/var/lib/postgresql/data
    ports:
      - "27017:27017"

volumes:
  asktogether-db:
